# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4a7a338bd9bc8e9831bd20712616fc79500268523fff4c93c31efb77d75c3fb3c1336d3603e2e936758baa5d383e5323807cb21c7f930a5538ecf45840c66c2

test:
  secret_key_base: e40cc0ed8e92eb4afede0844be382f7d3cd9a4d3ba60b52d10904f0c98225d4dc3ac1f7263417c3b2614cf6626299e5db64c560936c8007e8fab50449145f7e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
